onsport/blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('blog/', views.blog_list, name='blog_list'),
    path('blog/<slug:slug>', views.blog_category, name='blog_cat')
]

onsport/onsport/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog'))
]

onsport/blog/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Categories(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    category = models.ForeignKey(Categories, on_delete=models.SET_NULL,
                                 null=True, related_name='category')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='author')
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=200, default='Название')

    def __str__(self):
        return self.text[:30]

    class Meta:
        ordering = ['pub_date']


class Comment:
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             related_name='post_comment')
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='author_comment')
    text = models.CharField(max_length=5000)

    def __str__(self):
        return self.text[:30]

onsport/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Categories


def index(request):
    posts = Post.objects.all()
    context = {
        'posts': posts
    }
    template = 'blog/index.html'
    return render(request, template, context)


def blog_list(request):
    categories = Categories.objects.all()
    context = {
        'categories': categories
    }
    template = 'blog/blog_list.html'
    return render(request, template, context)


def blog_category(request, slug):
    category = get_object_or_404(Categories, slug=slug)
    posts = category.category.all()
    context = {
        'category': category,
        'posts': posts
    }
    template = 'blog/blog_category.html'
    return render(request, template, context)

onsport/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/my_style.css' %}">
  <title>{% block title%} Заголовок {% endblock %}</title>
</head>
<body>
  {% include "includes/header.html" %}
  <main>
    <div class="container py-5" >
      {% block content %} Контент{% endblock %}
    </div>
  </main>
  {% include "includes/footer.html" %}
</body>
</html>

onsport/templates/blog/blog_category.html
{% extends "base.html" %}
{% block title %} Блог {% endblock %}
{% block content %}
<h1>Все записи категории <span style="color:#8D40FF">{{ category }}</span></h1>
<div class="container p-1">
  {% for post in posts %}
   <div class="post">
     <p class="author_post"><b>{% if post.author.get_full_name %}{{post.author.get_full_name}}
       {% else %}{{ post.author }}{% endif %}</b></p>
      <p class="about_post">
        {{ post.pub_date }}<br>
        {% if post.category %}В категории: {{ post.category }}{% endif %}
      </p>
      <article>
        <h5 class="label"> {{ post.title }}</h5>
        <p class="post-text">{{ post.text }}</p>
     </article>
     <hr>
    </div>
  {% endfor %}
</div>

{% endblock %}

onsport/templates/blog/blog_list.html
{% extends "base.html" %}
{% block title %} Блог {% endblock %}
{% block content %}
  <div>
    {% for category in categories %}
    {{ category }}
    {% endfor %}
  </div>
{% endblock %}

onsport/templates/blog/index.html
{% extends "base.html" %}
{% block title %} onSport {% endblock %}
{% block content %}
<h1>Свежие записи</h1>
<div class="container p-1">
  {% for post in posts %}
  <div class="post">
    <p class="author_post"><b>{% if post.author.get_full_name %}{{post.author.get_full_name}}
      {% else %}{{ post.author }}{% endif %}</b></p>
    <p class="about_post">
      {{ post.pub_date }}<br>
      {% if post.category %}В категории: {{ post.category }}{% endif %}
    </p>
    <article>
      <h5 class="label"> {{ post.title }}</h5>
      <p class="post-text">{{ post.text }}</p>
    </article>
    <hr>
  </div>
  {% endfor %}
</div>
{% endblock %}

onsport/templates/includes/footer.html
<footer class="border-top text-center py-3">
    <p>© 2022 Copyright <span style="color:#ff4062">still</span>Sport</p>
</footer>

onsport/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light navbar-expand-lg" style="background-color: #8D40FF">
    <div class="container-fluid">
      <a class="navbar-brand" href=" {% url 'blog:index' %}">
        <span style="color:white"><span style="color:#ff4062">still</span>Sport</span>
      </a>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <a class="nav-item nav-link footer_label" style="color: white" href="{% url 'blog:blog_list' %}">Блог</a>
        <a class="nav-item nav-link footer_label" style="color: white" href="">Авторы</a>
        <a class="nav-item nav-link footer_label" style="color: white" href="">Форум</a>
        <a class="nav-item nav-link footer_label" style="color: white" href="">Тренировки</a>
      </div>
      <a class="nav-item nav-link footer_label" style="color: white" href="">Войти</a>
      <a class="nav-item nav-link footer_label" style="color: white" href="">Регистрация</a>
<!--      <ul class="nav nav-pills">-->
<!--        <li class="nav-item">-->
<!--          <a class="nav-link" style="color: white" href="">Блог</a>-->
<!--        </li>-->
<!--        <li class="nav-item">-->
<!--          <a class="nav-link" style="color: white" href="">Авторы</a>-->
<!--        </li>-->
<!--        <li class="nav-item">-->
<!--          <a class="nav-link" style="color: white" href="">Форум</a>-->
<!--        </li>-->
<!--        <li class="nav-item">-->
<!--          <a class="nav-link" style="color: white" href="">Тренировки</a>-->
<!--        </li>-->
<!--        <li class="nav-item">-->
<!--          <a class="nav-link" style="color: white" href="">Войти</a>-->
<!--        </li>-->
<!--      </ul>-->
    </div>
  </nav>
</header>